name: Deploy on push
on: [push]

permissions:
  contents: read

env:
  DEPLOY_FROM: github
  DEPLOY_REPOSITORY_URL: ${{ github.repositoryUrl }}
  CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

jobs:
  deploy-ci:
    runs-on: ubuntu-22.04
    env:
      DEPLOY_SHA: ${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.DEPLOY_SHA }}
      - name: Deploy to ci
        run: ./deploy.sh
        env:
          CF_CUSTOM_DOMAIN: ci.op3.dev
          CF_SCRIPT_NAME: op3-ci
          INSTANCE: ci
  deploy-dev:
    runs-on: ubuntu-22.04
    env:
      DEPLOY_SHA: ee3b3d4370df15b02262f1ddf9bcd4931272c300
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.DEPLOY_SHA }}
      - name: Deploy to dev
        run: ./deploy.sh
        env:
          CF_CUSTOM_DOMAIN: op3.dev
          CF_SCRIPT_NAME: op3-dev
          INSTANCE: dev
  deploy-prod:
    runs-on: ubuntu-22.04
    env:
      DEPLOY_SHA: ee3b3d4370df15b02262f1ddf9bcd4931272c300
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.DEPLOY_SHA }}
      - name: Deploy to prod
        run: ./deploy.sh
        env:
          CF_CUSTOM_DOMAIN: op3.st
          CF_SCRIPT_NAME: op3-prod
          INSTANCE: prod
