name: Deploy on push
on: [push]

permissions:
  contents: read

env:
  DEPLOY_FROM: github
  DEPLOY_REPOSITORY_URL: ${{ github.repositoryUrl }}
  CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
  PRODUCTION_DOMAIN: op3.dev

jobs:
  deploy-ci:
    runs-on: ubuntu-22.04
    env:
      DEPLOY_SHA: ${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.DEPLOY_SHA }}
      - name: Deploy to ci
        run: ./deploy.sh
        env:
          CF_CUSTOM_DOMAIN: ci.op3.dev
          CF_SCRIPT_NAME: op3-ci
          CF_BACKEND_DO_NAMESPACE: backend-do-ci
          CF_AE_DATASET: dataset1-ci
          CF_ANALYTICS_TOKEN: 031c86bb64214cb5a6b7aab02b5e1925
          INSTANCE: ci
          ADMIN_TOKENS: ${{ secrets.CI_ADMIN_TOKENS }}
          PREVIEW_TOKENS: ${{ secrets.CI_PREVIEW_TOKENS }}
  deploy-staging:
    runs-on: ubuntu-22.04
    env:
      DEPLOY_SHA: 5ab74a120c7a0e001c97a309d81505ff583d6180
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.DEPLOY_SHA }}
      - name: Deploy to staging
        run: ./deploy.sh
        env:
          CF_CUSTOM_DOMAIN: staging.op3.dev
          CF_SCRIPT_NAME: op3-staging
          CF_BACKEND_DO_NAMESPACE: backend-do-staging
          CF_AE_DATASET: dataset1-staging
          CF_ANALYTICS_TOKEN: 3c527d531d83451b8c89fba58678822a
          INSTANCE: staging
          ADMIN_TOKENS: ${{ secrets.STAGING_ADMIN_TOKENS }}
          PREVIEW_TOKENS: ${{ secrets.STAGING_PREVIEW_TOKENS }}
  deploy-prod:
    runs-on: ubuntu-22.04
    env:
      DEPLOY_SHA: 5ab74a120c7a0e001c97a309d81505ff583d6180
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.DEPLOY_SHA }}
      - name: Deploy to prod
        run: ./deploy.sh
        env:
          CF_CUSTOM_DOMAIN: ${{ env.PRODUCTION_DOMAIN }}
          CF_SCRIPT_NAME: op3-prod
          CF_BACKEND_DO_NAMESPACE: backend-do-prod
          CF_AE_DATASET: dataset1-prod
          CF_ANALYTICS_TOKEN: 7da609030515408f9ec8b16c529cecaf
          INSTANCE: prod
          ADMIN_TOKENS: ${{ secrets.PROD_ADMIN_TOKENS }}
          PREVIEW_TOKENS: ${{ secrets.PROD_PREVIEW_TOKENS }}
