name: Deploy on push
on: [push]

permissions:
  contents: read

env:
  DEPLOY_FROM: github
  DEPLOY_REPOSITORY_URL: ${{ github.repositoryUrl }}
  CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
  PRODUCTION_DOMAIN: op3.st

jobs:
  deploy-ci:
    runs-on: ubuntu-22.04
    env:
      DEPLOY_SHA: ${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.DEPLOY_SHA }}
      - name: Deploy to ci
        run: ./deploy.sh
        env:
          CF_CUSTOM_DOMAIN: ci.op3.dev
          CF_SCRIPT_NAME: op3-ci
          CF_BACKEND_DO_NAMESPACE: backend-do-ci
          CF_AE_DATASET: dataset1
          CF_ANALYTICS_TOKEN: 031c86bb64214cb5a6b7aab02b5e1925
          INSTANCE: ci
          ADMIN_TOKENS: ${{ secrets.CI_ADMIN_TOKENS }}
          PREVIEW_TOKENS: ${{ secrets.CI_PREVIEW_TOKENS }}
  deploy-dev:
    runs-on: ubuntu-22.04
    env:
      DEPLOY_SHA: 412d42c33cf2ceaea44070869979b22f9923fa36
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.DEPLOY_SHA }}
      - name: Deploy to dev
        run: ./deploy.sh
        env:
          CF_CUSTOM_DOMAIN: op3.dev
          CF_SCRIPT_NAME: op3-dev
          INSTANCE: dev
  deploy-prod:
    runs-on: ubuntu-22.04
    env:
      DEPLOY_SHA: 412d42c33cf2ceaea44070869979b22f9923fa36
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.DEPLOY_SHA }}
      - name: Deploy to prod
        run: ./deploy.sh
        env:
          CF_CUSTOM_DOMAIN: ${{ env.PRODUCTION_DOMAIN }}
          CF_SCRIPT_NAME: op3-prod
          INSTANCE: prod
