name: Deploy on push
on: [push]

permissions:
  contents: read

jobs:
  deploy-ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy to CI
        run: ./deploy.sh
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_CUSTOM_DOMAIN: ci.op3.dev
          INSTANCE: ci
          DEPLOY_REPOSITORY_URL: ${{ github.repositoryUrl }}
          DEPLOY_SHA: ${{ github.sha }}
          DEPLOY_FROM: github
